AWSTemplateFormatVersion: 2010-09-09
Description: |
  This CloudFormation Template was written for 
  testing Apache, Nginx and Flask running on same EC2. 
  Kittens Carousel Static Website will be 
  deployed on Amazon Linux 2 
  (ami-0a8b4cd432b1c3063) EC2 Instance with 
  custom security group which allows http 
  connections on port 80 and ssh port 22 from 
  anywhere. Kittens Carousel Static Website 
  is downloaded from my Public Github repository,
  then deployed on Apache Web Server.

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP for Apache Web Server and SSH for secure connection.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0

  WebServerHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a8b4cd432b1c3063
      InstanceType: t2.micro
      KeyName: firstkey
      AvailabilityZone: us-east-1c
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName} Stack
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          yum update -y
          yum install -y git
          pip3 install flask
          cd /home/ec2-user
          git clone https://github.com/agungor34/my-projects.git
          chown -R ec2-user.ec2-user /home/ec2-user/my-projects
          cd /home/ec2-user/my-projects/python/hands-on/flask/flask-04-handling-forms-POST-GET-Methods/Flask_GET_POST_Methods
          sed -i 's/app.run(debug=True)/app.run(host="0.0.0.0")/g' app.py
          python3 app.py &
          yum install -y httpd
          FOLDER="https://raw.githubusercontent.com/agungor34/my-projects/main/aws/projects/Project-101-kittens-carousel-static-website-ec2/static-web"
          cd /var/www/html
          wget $FOLDER/index.html
          wget $FOLDER/akif.png
          wget $FOLDER/cat0.jpg
          wget $FOLDER/cat1.jpg
          wget $FOLDER/cat2.jpg
          wget $FOLDER/cat3.png
          sed -i 's/Listen 80/Listen 8080/g' /etc/httpd/conf/httpd.conf
          systemctl start httpd
          amazon-linux-extras install nginx1 -y
          cd /usr/share/nginx/html
          chmod -R 777 /usr/share/nginx/html
          rm index.html
          wget https://raw.githubusercontent.com/awsdevopsteam/ngniex/master/index.html
          wget https://raw.githubusercontent.com/awsdevopsteam/ngniex/master/ryu.jpg
          systemctl start nginx

Outputs:
  WebsiteURL:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt WebServerHost.PublicDnsName
    Description: Kittens Carousel Application URL
